name: kirinyaga_agribusiness
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+19

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^7.0.0
  loading_animation_widget: ^1.2.0+4
  http: ^0.13.5
  email_validator: ^2.1.17
  infinite_scroll_pagination: ^4.0.0
  webview_flutter: ^3.0.4
  geolocator: ^9.0.2
  shared_preferences: ^2.1.0
  flutter_calendar_carousel: ^2.0.0
  flutter_form_builder: ^7.0.0-alpha.3
  table_calendar: ^3.0.9
  intl: ^0.18.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
